title: Yulong Chen's Homepage
page-top-title: Yulong Chen
top-section-bg-text: Computer Science
home-subtitle: Yulong Chen&ensp;|&ensp;陈雨龙
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
